#!/bin/bash
# Cores 1 2 3 4 have to be put as 1 2 4 8

# USB bus - All usb interrupts are sent to the fourth core
echo "8" > /proc/irq/62/smp_affinity
echo "8" > /proc/irq/63/smp_affinity

# Ethernet - All ethernet interrupts are sent to the third core
echo "4" > /proc/irq/40/smp_affinity
