#!/bin/bash
# this script enables squeezelite and disables mpd and mympd
#

systemctl enable squeezelite
systemctl start squeezelite

systemctl disable mpd mympd
systemctl stop mpd mympd

# need to re-work on this section
sed -i '/pidof squeezelite/s/^#//g' /usr/bin/archphile-optimize
sed -i '/pidof mpd/s/^/#/g' /usr/bin/archphile-optimize

archphile-optimize
