#!/bin/bash
######################Archphile Creation Script for Odroid C2############################
#########################################################################################
#Before running this script, you need to enable ssh root login with the following command
#and then log in as root:
#echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

clear
red='\e[0;31m'
NC='\e[0m'

# Deleting alarm user and changing Root password
echo -e "${red}Deleting alarm user...${NC}" 
#su
#cd /root
userdel -r alarm
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname archphile

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/motd-odroidc2 -O /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
# Opendns
nameserver 208.67.222.222 
nameserver 208.67.220.220
# Google
#nameserver 8.8.8.8
#nameserver 8.8.4.4
EOF
echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Disabling various modules
#echo -e "${red}Disabling various modules...${NC}" 
#cat > /etc/modprobe.d/blacklist.conf <<"EOF"
#blacklist w1_gpio
#blacklist spi_gpio
#blacklist gxbb_wdt
#EOF

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/archphile-network -O /etc/netctl/archphile-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable archphile-network

# Disabling ipv6
# "net.ipv6.conf.all.disable_ipv6=1" added throught archphile-optimize package 
sed -e '/::1/ s/^#*/#/' -i /etc/hosts
echo >>/etc/dhcpcd.conf
echo "#Disable ipv6 connectivity" >>/etc/dhcpcd.conf
echo "noipv6rs" >>/etc/dhcpcd.conf
echo "noipv6" >>/etc/dhcpcd.conf

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/recipe/master/files/ntp.conf -O /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/fstab-odroid -O /etc/fstab
echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Adding Archphile repository and installing needed packages
echo -e "${red}Adding Archphile Repository...${NC}" 
cat >> /etc/pacman.conf <<"EOF"
[archphile]
SigLevel = Never
Server = http://archphile.org/repo/aarch64-next/09971A

#[playground]
#SigLevel = Never
#Server = http://archphile.org/repo/playground/playground-aarch64
EOF

echo -e "${red}Updating system...${NC}" 
#pacman-key --init && pacman-key -r 0EEA0BE0 && pacman-key --lsign-key 0EEA0BE0
pacman -Syu --noconfirm
echo -e "${red}Installing audio related packages...${NC}" 
pacman -S alsa-utils mpd-archphile mpc mpdscribble ympd-archphile archphile-optimize upmpdcli-archphile shairport-sync brutefir alsacap mongoose librespot-archphile --noconfirm
echo -e "${red}Installing system related packages...${NC}" 
pacman -S samba cifs-utils nfs-utils udevil ntfs-3g htop avahi wpa_supplicant wireless_tools iw dhcpcd ethtool hd-idle lirc --noconfirm

echo -e "${red}Installing Mainline Kernel...${NC}"
 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/modify_odroid_c2_dtb.sh -O /usr/local/bin/modify_odroid_c2_dtb.sh
chmod +x /usr/local/bin/modify_odroid_c2_dtb.sh
pacman -R uboot-odroid-c2 --noconfirm
#rm /boot/boot.ini.pacsave
#pacman -U http://archphile.org/lab/odroidc2/packages/linux-aarch64-4.15.5-1-aarch64.pkg.tar.xz
#pacman -U http://archphile.org/lab/odroidc2/packages/linux-aarch64-headers-4.15.5-1-aarch64.pkg.tar.xz
pacman -Sy linux-aarch64 uboot-odroid-c2-mainline uboot-tools dtc
bash /usr/local/bin/modify_odroid_c2_dtb.sh
wget https://raw.githubusercontent.com/archphile/recipe/master/files/boot.txt -O /boot/boot.txt
cd /boot
./mkscr
cd /root

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db which s-nail licenses jfsutils gettext logrotate --noconfirm
pacman -Scc

# Bypassing new User=mpd systemd configuration 
#echo -e "${red}Fetching user.conf in order to bypass User=mpd...${NC}" 
#mkdir /etc/systemd/system/mpd.service.d
#wget https://raw.githubusercontent.com/archphile/recipe/master/files/user.conf -O /etc/systemd/system/mpd.service.d/user.conf

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Enabling systemd services
echo -e "${red}Enabling needed Systemd services...${NC}" 
systemctl enable mpd
systemctl enable ympd
systemctl enable archphile
systemctl enable avahi-daemon

# Creating stuff for MPD
echo -e "${red}Creating directories needed by MPD and downloading webradios...${NC}" 
mkdir /mnt/nas-nfs
mkdir /mnt/nas-samba
mkdir /mnt/usb-disk
mkdir /var/lib/mpd/music
cd /var/lib/mpd/music
ln -s /mnt/nas-nfs
ln -s /mnt/nas-samba
ln -s /mnt/usb-disk
wget https://github.com/archphile/recipe/raw/master/files/webradio.tar.gz
tar xvfz webradio.tar.gz
rm webradio.tar.gz
gpasswd -a mpd audio
chown -R mpd:audio /var/lib/mpd

# Alsa configuration using nrpacks, a command recently reintroduced in odroid kernels
#echo -e "${red}Creating Alsa configuration...${NC}" 
#cat > /etc/modprobe.d/alsa-base.conf <<"EOF"
#options snd-usb-audio nrpacks=1
#EOF

# setting the USB Dac as default sound card
echo -e "${red}Setting the USB DAC as the default sound card...${NC}" 
cat > /etc/asound.conf <<"EOF"
pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw
        card 0
}
EOF

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/udevil.conf -O /etc/udevil/udevil.conf
systemctl enable devmon@root

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
rm -R /var/log

# Applying various tweaks/mods
echo -e "${red}Applying various tweaks/mods ...${NC}" 
echo "Archphile \r (\l)" > /etc/issue
sed -i 's/#Color/Color/' /etc/pacman.conf

# settings for fetching local cover art using Mpdroid and Mpod
echo -e "${red}Making symlinks for fetching local cover art${NC}" 
mkdir -p /var/www/covers
mkdir -p /var/www/Music
ln -s /var/lib/mpd/music /var/www/covers
ln -s /var/lib/mpd/music /var/www/Music

# disks spin-down configuration
echo -e "${red}Fetching udev rules for hdparm...${NC}" 
mkdir /opt/archphile
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-onedisk -O /opt/archphile/50-hdparm.rules-onedisk
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-manydisks -O /opt/archphile/50-hdparm.rules-manydisks
wget https://raw.githubusercontent.com/archphile/recipe/master/files/hd-idle -O /etc/conf.d/hd-idle

# sharing usb disks with samba configuration
echo -e "${red}Fetching samba configuration for sharing usb disks...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/smb.conf -O /etc/samba/smb.conf
echo -e "${red}In order to share your usb disk please enable and start smbd and nmbd service...${NC}"

# Setting configuration for shairport-sync
echo -e "${red}Setting shairport-sync configuration..${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/shairport-sync.conf -O /etc/shairport-sync.conf

# IRQ affinity options
echo -e "${red}Adding optional IRQ affinity options...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/irq-archphile-odroidc2 -O /usr/bin/irq-archphile
chmod +x /usr/bin/irq-archphile

# Set USB DAC as default MPD soundcard
#echo -e "${red}Setting default sound card in mpd.conf...${NC}" 
#sed -i 's/^device          "hw:0,0".*/device          "hw:1,0"/' /etc/mpd.conf

# Set custom boot.ini configuration
#echo -e "${red}Setting custom boot.ini...${NC}"
#wget https://raw.githubusercontent.com/archphile/recipe/master/files/boot.ini.c2 -O /boot/boot.ini

# Disable haveged and enable rngd
#echo -e "${red}Disabling haveged and enabling rngd...${NC}" 
#systemctl disable haveged 
#pacman -Rcsn haveged --noconfirm
#touch /etc/conf.d/rngd
#echo 'RNGD_OPTS="-o /dev/random -r /dev/hwrng"' > /etc/conf.d/rngd
#systemctl enable rngd

# Applying various tweaks by default
echo -e "${red}Enabling IRQ affinity...${NC}" 
sed -i '/irq-archphile/s/^#//g' /usr/bin/archphile-optimize
echo -e "${red}Setting various processes to be run on specific cores...${NC}" 
sed -i '/pidof mpd/s/^#//g' /usr/bin/archphile-optimize
sed -i '/0 $(pidof ympd)/s/^#//g' /usr/bin/archphile-optimize
echo -e "${red}Disabling heartbeat blue led...${NC}" 
sed -i '/alive/s/^#//g' /usr/bin/archphile-optimize 

# system cleanup
echo -e "${red}Cleaning up system...${NC}" 
rm /etc/ssh/ssh_host_*
rm /root/archphile-create-script*

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 
