#!/bin/bash
######################Lirc Configuration Script for Odroid C1+ and Apple remote############################
clear
red='\e[0;31m'
NC='\e[0m'

# Copying needed files
echo -e "${red}Copying the needed configuration files...${NC}" 
mkdir /etc/conf.d
wget https://raw.githubusercontent.com/archphile/recipe/master/lirc-configuration/lircd.conf -O /etc/conf.d/lircd.conf
wget https://raw.githubusercontent.com/archphile/recipe/master/lirc-configuration/apple.conf -O /etc/lirc/lircd.conf.d/lircd.conf
wget https://raw.githubusercontent.com/archphile/recipe/master/lirc-configuration/lircrc -O /etc/conf.d/lircrc
wget https://raw.githubusercontent.com/archphile/recipe/master/lirc-configuration/irexec.service -O /usr/lib/systemd/system/irexec.service
wget https://raw.githubusercontent.com/archphile/recipe/master/lirc-configuration/module -O /etc/modules-load.d/lircd.conf

# Loading the module manually in order not to need a reboot
echo -e "${red}Loading the needed modules...${NC}" 
modprobe meson_ir

# Enabling and starting systemd services
echo -e "${red}Enabling and starting systemd services...${NC}" 
systemctl enable lircd irexec
systemctl start lircd irexec


